### ISSUE TITLE
Laser is not implemented

### ISSUE THREAD

**Issue by ghost** [openUC2/imswitchclient#2]
Pleas implement the lasercontroller, too @beniroquai

**Comment by beniroquai** [comment]
I have implemented in [4bbc8eb](https://github.com/openUC2/imswitchclient/commit/4bbc8ebf6aaa493883a5a5eecb6db5624db4982e)

Interestingly, I didn't get a message - maybe you have to assign me, too. Anyway. Will close the issue since it's done. Feel free to ask for more parts of the controllers :)
